version: '3.3'

services:

  default:
    container_name: processors
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - NODE_ENV=development

  test:
    command: npm run test
    build: .
    volumes:
      - '.:/usr/src/app'

  task:
    build: .
    volumes:
      - '.:/usr/src/app'
